//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 11:43:13 PM GMT 
//


package model.lidc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}noduleID"/>
 *         &lt;element ref="{}roi" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noduleID",
    "roi"
})
@XmlRootElement(name = "blindedReadNodule")
public class BlindedReadNodule {

    @XmlElement(required = true)
    protected String noduleID;
    @XmlElement(required = true)
    protected List<Roi> roi;

    /**
     * Gets the value of the noduleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoduleID() {
        return noduleID;
    }

    /**
     * Sets the value of the noduleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoduleID(String value) {
        this.noduleID = value;
    }

    /**
     * Gets the value of the roi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Roi }
     * 
     * 
     */
    public List<Roi> getRoi() {
        if (roi == null) {
            roi = new ArrayList<Roi>();
        }
        return this.roi;
    }

}
