//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 11:43:13 PM GMT 
//


package model.lidc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subtlety" type="{}Subtlety"/>
 *         &lt;element name="internalStructure" type="{}InternalStructure"/>
 *         &lt;element name="calcification" type="{}Calcification"/>
 *         &lt;element name="sphericity" type="{}Sphericity"/>
 *         &lt;element name="margin" type="{}Margin"/>
 *         &lt;element name="lobulation" type="{}Lobulation"/>
 *         &lt;element name="spiculation" type="{}Spiculation"/>
 *         &lt;element name="texture" type="{}Texture"/>
 *         &lt;element name="malignancy" type="{}Malignancy"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subtlety",
    "internalStructure",
    "calcification",
    "sphericity",
    "margin",
    "lobulation",
    "spiculation",
    "texture",
    "malignancy"
})
@XmlRootElement(name = "characteristics")
public class Characteristics {

    @XmlSchemaType(name = "unsignedByte")
    protected short subtlety;
    @XmlElement(defaultValue = "1")
    @XmlSchemaType(name = "unsignedByte")
    protected short internalStructure;
    @XmlSchemaType(name = "unsignedByte")
    protected short calcification;
    @XmlSchemaType(name = "unsignedByte")
    protected short sphericity;
    @XmlSchemaType(name = "unsignedByte")
    protected short margin;
    @XmlSchemaType(name = "unsignedByte")
    protected short lobulation;
    @XmlSchemaType(name = "unsignedByte")
    protected short spiculation;
    @XmlSchemaType(name = "unsignedByte")
    protected short texture;
    @XmlSchemaType(name = "unsignedByte")
    protected short malignancy;

    /**
     * Gets the value of the subtlety property.
     * 
     */
    public short getSubtlety() {
        return subtlety;
    }

    /**
     * Sets the value of the subtlety property.
     * 
     */
    public void setSubtlety(short value) {
        this.subtlety = value;
    }

    /**
     * Gets the value of the internalStructure property.
     * 
     */
    public short getInternalStructure() {
        return internalStructure;
    }

    /**
     * Sets the value of the internalStructure property.
     * 
     */
    public void setInternalStructure(short value) {
        this.internalStructure = value;
    }

    /**
     * Gets the value of the calcification property.
     * 
     */
    public short getCalcification() {
        return calcification;
    }

    /**
     * Sets the value of the calcification property.
     * 
     */
    public void setCalcification(short value) {
        this.calcification = value;
    }

    /**
     * Gets the value of the sphericity property.
     * 
     */
    public short getSphericity() {
        return sphericity;
    }

    /**
     * Sets the value of the sphericity property.
     * 
     */
    public void setSphericity(short value) {
        this.sphericity = value;
    }

    /**
     * Gets the value of the margin property.
     * 
     */
    public short getMargin() {
        return margin;
    }

    /**
     * Sets the value of the margin property.
     * 
     */
    public void setMargin(short value) {
        this.margin = value;
    }

    /**
     * Gets the value of the lobulation property.
     * 
     */
    public short getLobulation() {
        return lobulation;
    }

    /**
     * Sets the value of the lobulation property.
     * 
     */
    public void setLobulation(short value) {
        this.lobulation = value;
    }

    /**
     * Gets the value of the spiculation property.
     * 
     */
    public short getSpiculation() {
        return spiculation;
    }

    /**
     * Sets the value of the spiculation property.
     * 
     */
    public void setSpiculation(short value) {
        this.spiculation = value;
    }

    /**
     * Gets the value of the texture property.
     * 
     */
    public short getTexture() {
        return texture;
    }

    /**
     * Sets the value of the texture property.
     * 
     */
    public void setTexture(short value) {
        this.texture = value;
    }

    /**
     * Gets the value of the malignancy property.
     * 
     */
    public short getMalignancy() {
        return malignancy;
    }

    /**
     * Sets the value of the malignancy property.
     * 
     */
    public void setMalignancy(short value) {
        this.malignancy = value;
    }

}
