//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 11:43:13 PM GMT 
//


package model.lidc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LobarLocation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LobarLocation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RUL"/>
 *     &lt;enumeration value="RML"/>
 *     &lt;enumeration value="RLL"/>
 *     &lt;enumeration value="LUL"/>
 *     &lt;enumeration value="LLL"/>
 *     &lt;enumeration value="null"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LobarLocation")
@XmlEnum
public enum LobarLocation {

    RUL("RUL"),
    RML("RML"),
    RLL("RLL"),
    LUL("LUL"),
    LLL("LLL"),
    @XmlEnumValue("null")
    NULL("null");
    private final String value;

    LobarLocation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LobarLocation fromValue(String v) {
        for (LobarLocation c: LobarLocation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
