//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 11:43:13 PM GMT 
//


package model.lidc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}annotationVersion"/>
 *         &lt;element ref="{}servicingRadiologistID"/>
 *         &lt;choice>
 *           &lt;element ref="{}unblindedReadNodule" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}blindedReadNodule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}nonNodule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotationVersion",
    "servicingRadiologistID",
    "unblindedReadNodule",
    "blindedReadNodule",
    "nonNodule"
})
@XmlRootElement(name = "readingSession")
public class ReadingSession {

    @XmlElement(required = true, defaultValue = "3.12")
    protected String annotationVersion;
    @XmlElement(required = true)
    protected String servicingRadiologistID;
    protected List<UnblindedReadNodule> unblindedReadNodule;
    protected List<BlindedReadNodule> blindedReadNodule;
    protected List<NonNodule> nonNodule;

    /**
     * Gets the value of the annotationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationVersion() {
        return annotationVersion;
    }

    /**
     * Sets the value of the annotationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationVersion(String value) {
        this.annotationVersion = value;
    }

    /**
     * Gets the value of the servicingRadiologistID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicingRadiologistID() {
        return servicingRadiologistID;
    }

    /**
     * Sets the value of the servicingRadiologistID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicingRadiologistID(String value) {
        this.servicingRadiologistID = value;
    }

    /**
     * Gets the value of the unblindedReadNodule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unblindedReadNodule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnblindedReadNodule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnblindedReadNodule }
     * 
     * 
     */
    public List<UnblindedReadNodule> getUnblindedReadNodule() {
        if (unblindedReadNodule == null) {
            unblindedReadNodule = new ArrayList<UnblindedReadNodule>();
        }
        return this.unblindedReadNodule;
    }

    /**
     * Gets the value of the blindedReadNodule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blindedReadNodule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlindedReadNodule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlindedReadNodule }
     * 
     * 
     */
    public List<BlindedReadNodule> getBlindedReadNodule() {
        if (blindedReadNodule == null) {
            blindedReadNodule = new ArrayList<BlindedReadNodule>();
        }
        return this.blindedReadNodule;
    }

    /**
     * Gets the value of the nonNodule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonNodule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonNodule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNodule }
     * 
     * 
     */
    public List<NonNodule> getNonNodule() {
        if (nonNodule == null) {
            nonNodule = new ArrayList<NonNodule>();
        }
        return this.nonNodule;
    }

}
