//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 11:43:13 PM GMT 
//


package model.lidc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}imageZposition"/>
 *         &lt;element ref="{}imageSOP_UID"/>
 *         &lt;element ref="{}inclusion"/>
 *         &lt;element ref="{}edgeMap" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imageZposition",
    "imageSOPUID",
    "inclusion",
    "edgeMap"
})
@XmlRootElement(name = "roi")
public class Roi {

    @XmlElement(required = true)
    protected BigDecimal imageZposition;
    @XmlElement(name = "imageSOP_UID", required = true)
    protected String imageSOPUID;
    @XmlElement(required = true)
    protected String inclusion;
    @XmlElement(required = true)
    protected List<EdgeMap> edgeMap;

    /**
     * Gets the value of the imageZposition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImageZposition() {
        return imageZposition;
    }

    /**
     * Sets the value of the imageZposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImageZposition(BigDecimal value) {
        this.imageZposition = value;
    }

    /**
     * Gets the value of the imageSOPUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageSOPUID() {
        return imageSOPUID;
    }

    /**
     * Sets the value of the imageSOPUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageSOPUID(String value) {
        this.imageSOPUID = value;
    }

    /**
     * Gets the value of the inclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInclusion() {
        return inclusion;
    }

    /**
     * Sets the value of the inclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInclusion(String value) {
        this.inclusion = value;
    }

    /**
     * Gets the value of the edgeMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edgeMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdgeMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgeMap }
     * 
     * 
     */
    public List<EdgeMap> getEdgeMap() {
        if (edgeMap == null) {
            edgeMap = new ArrayList<EdgeMap>();
        }
        return this.edgeMap;
    }

}
